import { imagePath } from "../lib/image";

export const weekendDeals = [
  {
    id: 1,
    title: "Seaside Serenity Villa",
    location: "Amalfi Coast, Italy",
    rating: 4.0,
    reviewText: "Very Good",
    reviews: 160,
    priceOld: 250,
    priceNew: 175,
    imageUrl: imagePath("weekly-deal-card/amalfi-coast.jpg"),
  },
  {
    id: 2,
    title: "Mountain Retreat",
    location: "Swiss Alps, Switzerland",
    rating: 4.8,
    reviewText: "Excellent",
    reviews: 210,
    priceOld: 400,
    priceNew: 299,
    imageUrl: imagePath("weekly-deal-card/swiss-alps.jpg"),
  },
  {
    id: 3,
    title: "Ocean View Hotel",
    location: "Malé, Maldives",
    rating: 4.5,
    reviewText: "Great",
    reviews: 85,
    priceOld: 550,
    priceNew: 420,
    imageUrl: imagePath("weekly-deal-card/maldives.jpg"),
  },
  {
    id: 4,
    title: "Sunset Cliff Suite",
    location: "Santorini, Greece",
    rating: 4.7,
    reviewText: "Excellent",
    reviews: 185,
    priceOld: 450,
    priceNew: 320,
    imageUrl: imagePath("weekly-deal-card/santorini.jpg"),
  },
  {
    id: 5,
    title: "Desert Oasis",
    location: "Dubai, UAE",
    rating: 4.9,
    reviewText: "Exceptional",
    reviews: 320,
    priceOld: 600,
    priceNew: 450,
    imageUrl: imagePath("weekly-deal-card/dubai.jpg"),
  },
];
